apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: Recreate       # Specify the Recreate strategy
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: rogersacchelli/frontend:1.0.3
          ports: 
            - containerPort: 3000
          imagePullPolicy: Always
          env:
            - name: NEXT_PUBLIC_REST_ENDPOINT
              value: "192.168.1.130:30003"
            - name: NEXT_PUBLIC_WS_ENDPOINT
              value: "192.168.1.130:30002"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001
  type: NodePort
