apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: Recreate # Specify the Recreate strategy
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: rogersacchelli/frontend:1.0.3
          resources:
                requests:
                  memory: 64Mi
                  cpu: 100m
                limits:
                  memory: 256Mi
                  cpu: 200m
          ports:
            - containerPort: 3000
          imagePullPolicy: IfNotPresent
          env:
              - name: NEXT_PUBLIC_REST_ENDPOINT
                value: "/api"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
        #externalTrafficPolicy: Local
  type: ClusterIP
