apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: Recreate       # Specify the Recreate strategy
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: rogersacchelli/frontend:latest
          ports: 
            - containerPort: 3000
          imagePullPolicy: IfNotPresent
          env:
            - name: NEXT_PUBLIC_REST_ENPOINT
              value: "tcp://10.10.10.10:1234"
            - name: NEXT_PUBLIC_WS_ENPOINT
              value: "tcp://10.11.12.13:2343"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001
  type: NodePort
